
pipeline {
    agent any

    stages {
        stage('cypress_auto_test') {

            steps {
                bat '''cd /d "D:\\Software Install\\Jenkins-work\\workspace\\test-cypress-project\\e2e\\v24.1"
                       npx cypress run --spec cypress/scenarios/regression/qto/*'''
            }
			
        }
    }
	
	post {
        success {
            // Send email
            emailext body: '''<html>
                            <h1>total cases: ${TEST_COUNTS, var="total"}  </h1>
                            <h1>pass cases:  ${TEST_COUNTS, var="pass"} </h1>
                            <h1>fail cases: ${TEST_COUNTS, var="fail"} </h1>

                            </html>''',
                             subject: 'cypress-auto-reports',
                              to: 'c15986413354@163.com'
        }
}
	
	
}
