namespace CommonLocators {
  export enum CommonContainerElements {
    MAXIMIZE = "button[title='Maximize']",
    MINIMIZE = "[class*='ico-minimized2']",
    BOQ_FOLDER_ICON = "[class*='ico-folder-doc']",
    LOOKUP_GRID_CONTAINER="[class*='lookup-grid-container']" 
  }

  export enum CommonModalElements {
    MODAL_DIALOG_CLASS = "[class*='modal-dialog']",
    MODAL_CONTENT_CLASS = "[class*='modal-content']",
    MODEL_ITEM_FIELD = `[class*="item-field_MdcMaterialFk"]`,
    MODAL_RESIZABLE = `[class*="modal-content ui-resizable"]`,
    CHANGE_ORDERS = `[class*="form-control ng-pristine ng-valid"]`,
    MODAL_FLEX = "[class='category-tree ng-scope']",
    MODAL_CATEGORY = "[class*='ticket-categories']",
    FOOTER = "[class*='ms-sv-cart-item-count']",
    SUB_CONTAINER_IN_MODEL = "[ng-controller='boqMainStructureDetailsController'] [class*='subview-container']",
    MODAL_TITLE = "[class*='modal-title']",
    MODAL_FOOTER = "[class*='modal-footer']",
    MODAL_ROW_CLASS = "spaceToUp",
    MODAL_BODY = "[class*='modal-body']",
    MULTIPLE_SELECTIONS_0_ITEMS_SELECTED="Multiple Selection - 0 Items Selected"
  }
  export enum  ModalInput{
    lookup_Cell=`[class*="input-group-content"]`,
    text_Cell='input[data-ng-model="entity.',
    modal_label=`.modal-dialog .platform-form-row label`
  }


  export enum CommonLabels {
    WorkOperationType = "Work Operation Type",
    JOB = "Job",
    CONFIGURATION = "Configuration",
    STREET = "Street",
    ZIP_CODE = "Zip Code",
    COUNTRY = "Country",
    SELECT = "Select",
    BUSINESS_PARTNER = "Business Partner",
    OUTLINE_SPECIFICATION = "Outline Specification",
    UOM = "UoM",
    UNIT_RATE = "Unit Rate",
    LANGUAGE = "Language",
    UI_LANGUAGE = "UI Language",
    USER_DATA_LANGUAGE = "User Data Language",
    BILL_TYPE = "Type",
    CONTRACT = "Contract",
    DESCRIPTION = "Description",
    CLERK = "Clerk",
    CONTRACT_TYPE = "Contract Type",
    COPY_FROM = "Copy From",
    WIC_GROUP = "WIC Group",
    BOQ_SELECTION = "BoQ Selection",
    BOQ_STRUCTURE_OUTLINE_SPEC = "BoQ Structure Outline Specification",
    SOURCE_BOQ_OUTLINE_SPEC = "Source Outline Specification",
    PROJECT = "Project",
    SOURCE_BOQ = "Source BoQ",
    TARGET_WIC_GROUP = "Target WIC Group",
    REFERENCE_NO = "Reference No.",
    SELECT_ESTIMATE_SCOPE = "Select Estimate Scope",
    SELECT_PACKAGES = "Select Packages",
    SELECT_RESOURCES = "Select Resources",
    CREATE_ACCESS_RIGHT = "Create Access Right",
    PROJECT_CHANGE = "Project Change",
    RUBRIC_CATEGORY = "Rubric Category",
    CHANGE_TYPE = "Change Type",
    CHANGE_REASON = "Change Reason",
    CHANGE_ORDER_CONTRACT_DESC = "Change Order Contract Desc",
    CONTRACT_STATUS = "Contract Status",
    PES = "PES",
    QUOTATION = "Quotation",
    REQUISITION = "Requisition",
    MATERIAL_SEARCH = "Material Search",
    STRUCTURE_TYPE = "Structure Type",
    HEADER_TEXT = "Header Text",
    EDIT_ESTIMATE_TYPE = "Edit Estimate Type",
    IS_COLUMN_CONFIGURE_ACTIVATED = "Is Column Configure Activated",
    EDIT_TYPE = "Edit Type",
    ESTIMATE_STRUCTURE_CONFIG_DETAILS = "Estimate Structure Config Details",
    VOUCHER_NO = "Voucher No",
    PROCUREMENT_TYPE = "Procurement Type",
    REQUISITION_OWNER = "Requisition Owner",
    RESPONSIBLE = "Responsible",
    CONTROLLING_UNIT = "Controlling Unit",
    DESCRIPTION_PREFIX = "Description Prefix",
    START_DATE = "Start Date",
    END_DATE = "End Date",
    REPEAT = "Repeat",
    TIME_REQUIRED = "Time Required",
    ROUND_UP_QUANTITY = "Round up the Quantity",
    DATE_DELIVERED = "Date Delivered",
    CITY = "City",
    ADDRESS = "Address",
    VENDOR = "Vendor:",
    MATERIAL_TYPE = "Material Type",
    PRICE_LIST = "Price List",
    TYPE = "type",
    CATALOG = "Catalog",
    ATTRIBUTE = "Attributes",
    BRANCH_DESCRIPTION = "Branch Description",
    CHECKBOX_LIST_GROUP_TYPE = "Checkbox List Group Type",
    PLANT = "Plant",
    PLANT_CODE = "Plant Code",
    PLANT_GROUP = "Plant Group",
    PLANT_KIND = "Plant Kind",
    PLANT_TYPE = "Plant Type",
    PLANT_DESCRIPTION = "Plant Description",
    SET_THE_REPORTING_DATE_TO = "Set the reporting date to",
    WHERE_CONTRACT_STATUS_IS = "Where the contract status is",
    DISTANCE = "Distance",
    REGION = "Region",
    REQUIRED_DATE = "Required Date:",
    SCOPE = "Scope",
    REPLACE_FROM = "Replace from",
    FACTOR = "Factor",
    IS_BASE = "Is Base",
    RFQ_HEADER = "RfQ Header",
    LENGTH_DIMENSION = "Length Dimension",
    BOQ_SOURCE = "BoQ Source",
    BOQS = "BoQs",
    TOTAL_OC_NET = "Total OC (Net)",
    TOTAL_CONFIGURE_DETAILS = "Totals Configure Details",
    TOTAL_CONFIGURE_EDIT_TYPE = "Edit Type",
    STRUCTURE = "Structure",
    AMOUNT = "Amount",
    PROCUREMENT_STRUCTURE = "Procurement Structure",
    BUDGET = "Budget",
    COSTCODES = "Cost Codes",
    BP_STATUS = "Status",
    SELECTION = "Selection",
    PREVIOUS_BILL = "Previous Bill",
    PROJECT_NAME = "Project Name",
    CHANGE_ORDER = "Change Order",
    CHANGE_ORDER_CODE = "New Change Order Code",
    CHANGE_ORDER_DESCRIPTION = "New Change Order Description",
    RADIO = "radio",
    ENTIRE_ESTIMATE = "Entire Estimate",
    GRAND_TOTAL = "Grand Total",
    X_FACTOR = "x Factor",
    SOURCE_LEADING_STRUCTURE = "Source Leading Structure",
    ADDITIONAL_SETTING = "Additional Setting",
    COPYING_DESCRIPTION_AND_USER_DEFINED = "Copying Description and User Defined",
    COPYING_ASSIGNMENT = "Copying Assignment",
    CREATE_NEW = "Create New",
    BASIC_SETTING = "Basic setting",
    PROJECT_NUMBER = "Project Number",
    NAME = "Name",
    BUDGET_FROM = "Budget From",
    NEW_RECORD = "New Record",
    GENERATE_UPDATE_BASE_COST = "Generate/Update Base Cost",
    UPDATE_REVENUE = "Update Revenue",
    DISTRIBUTE_BY = "Distribute By",
    KIND = "kind",
    SUCCESSORS = "Successors",
    CREATE_RELATIONS = "Create Relations",
    GENERATE_ACTIVITIES = "Generate Activities",
    GENERATE_ACTIVITIES_FROM_ONE_ACTIVE_ESTIMATE = "Generate Activities From One Active Estimate",
    GENERATE_ACTIVITIES_FREE_SCHEDULE_NO_LINK_WITH_ESTIMATE="Generate Activities - free Schedule (no link with Estimate)",
    EVALUATION_SCHEMA = "Evaluation Schema",
    REMARK = "Remark",
    ROLE = "Role",
    SERVICE = "Service",
    AREA_CODE = "Area Code",
    PHONE_NUMBER = "Phone Number",
    TELEPHONE = "Telephone",
    EXTENSION = "Extension",
    ESTIMATE_TYPE_CONFIGURATION = "Estimate Type Configuration",
    NEW_ESTIMATE_TYPE = "New Estimate Type",
    UPDATE_ESTIMATE = "Update Estimate",
    ITEM_ASSIGNMENT = "Item Assignment",
    FUNCTION_TYPE = "Function Type",
    IGNORE_CURRENT_ELEMENT_JOB = "Ignore Current Element Job",
    REPLACE_WITH_ELEMENT = "Replace With Element",
    REPLACE_DETAILS = "Replace Details",
    RESOURCE_TYPE = "Resource Type",
    CURRENT_ELEMENT="Current Element",
    CURRENT_ELEMENT_JOB="Current Element Job",
    CHANGE_VALUE = "Change Value",
    BASIC_SETTING_CAPS = "Basic Setting",
    BID = "Bid",
    INCLUDE_INACTIVE_ITEMS = "Include inactive items",
    MODIFY_DETAILS = "Modify Details",
    ASSEMBLY_CATEGORY = "Assembly Category",
    RADIO_HIGHLETED_LINE_ITEM = "Highlighted Line Item",
    RADIO_SPLIT_QUANTITY = "Split Quantity",
    PROCUREMENT_STRUCTURE_SMALL = "Procurement structure",
    BILL_TO="Bill To",
    UPDATED_PLANNED_QUANTITY="Update Planned Quantity",
    IQ_QUANTITY_UPDATE="IQ Quantity Update",
    UPDATE_BILLING_QUANTITY="Update Billing Quantity",
    ESTIMATE_CONFIGURATION="Estimate Configuration",
    ESTIMATE_STRUCTURE="Estimate Structure",
    IBAN = "IBAN",
    START="Start",
    MAIN_CONTRACT="Main Contract",
    SELECT_CONTRACT_HEADER_SCOPE="Select Contract Header Scope",
    DISTRIBUTE_BASED_ON="Distribute based on",
    LAYOUT_6="layout6",
    SYSTEM_OPTION="System Option",
    TEMPLATE_PROJECT="Template Project",
    SCHEDULE="Schedule",
    CODE="Code",
    UPDATE_THE_EXISTING_ITEMS="Update the existing items",
    HIGHLIGHTED_ASSEMBLY="Highlighted Assembly",
    CO2_SOURCE="CO2 Source",
    CO2="CO2",
    UPDATE_MATERIAL_PRICES="Update Material Prices",
    BASE="Base",
    ENTERPRISE_CATALOG_CONFIGURATION="Enterprise Catalog Configuration",
    CUSTOMIZING="Customizing",
    CONTRACT_SALES="Contract Sales",
    MAIN_BID="Main Bid",
    STRUCTURE_SETTINGS="Structure Settings",
    BASED_ON_MAJOR_LINE_ITEMS="Based on major line items",
    BASED_ON_PROJECT_CHANGE_LINE_ITEMS="Based on project change line items",
    TYPE_CAPS="Type",
    CREATE="Create",
    WIP="WIP",
    SELECTED_PLANTS_ONLY='Selected Plant(s) only',
    SELECT_A_JOB="Select a Job",
    JOB_CARD="Job Card",
    CREATE_A_NEW_LOGISTIC_JOB="Create a new Logistic Job",
    FINISH="Finish",
    UNDER_MAINTENANCE="Under Maintenance",
    DONE="Done",
    IS_DUE="Is Due",
    REMARKS="Remarks",
    BASIC_DATA="Basic Data",
    ASSIGN_BUSINESS_PARTNER="Assign Business Partner",
    REQUISITION_STATUS= "Requisition Status",
    MODAL_OVERWRITE_RADIO_BUTTON= "Overwrite the only requisition with entire sub package(not only change)*",
    MULTI_PACKAGE_ASSIGNMENT_MODEL="Multi Package Assignment Model",
    PROJECT_DOCUMENT_TYPE="Project Document Type",
    DELETE="Delete",
    EVALUATE_CURRENT_PACKAGE="Evaluate current package",
    MATERIAL_PACKAGE="Material Package",
    STANDARD_CUMULATIVE="Standard Cumulative",
    CODE_FORMAT="Code Format",
    LEVEL_1 ="Level 1",
    SORTING_LEVEL_1="Sorting Level 1",
    PROCUREMENT_CONFIGURATION="Procurement Configuration",
    CONSOLIDATION_LEVEL="Consolidation Level",
    REGIONAL="Regional",
    TICKET_ORDER="Ticket Order",
    CRITERIA_1 ="Criteria 1",
    KIND_CAPS="Kind",
    BRANCH="Branch",
    CONSTRUCTION_SYSTEM_MASTER ="Construction System Master",
    SERVICE_REQ="Service REQ",
    PROCUREMENT_SCHEDULE="Procurement Schedule",
    UPDATE_PROCUREMENT_SCHEUDLE_FOR_CURRENT_PACKAGE="Update procurement schedule for current package",
    UPDATE_EVENTS_FOR_CURRENT_PACKAGE_FROM_SCHEUDLE="Update events for current package from Scheduling",
    EXISTED_CATALOG="Existed Catalog",
    BILL_NO="Bill No",
    CALL_OFF_ORDER="Call-Off Order",
    QUOTATION_STATUS="Quotation Status",
    CREATE_NEW_BOQ="Create new BoQ",
    ALLOCATED_FROM="Allocated From",
    ADVANCED_CRITERIA="Advanced Criteria",
    PARAMETERS = "Parameters",
    RP_4 = "RP_4",
    RP_2 = "RP_2",
    GA_4 = "GA_4",
    GA_2 = "GA_2",
    PLANT_PRICING_GROUP="Plant Pricing Group",
    TEMPLATE="Template",
    CONTROL_TEMPLATE="Control Template",
    RECEIVING_JOB="Receiving Job",
    WORK_OPERATION_TYPE="Work Operation Type",
    ASSIGNED_LEVEL = "Assigned Level",
    STRUCTURE_OR_ROOT="Structure or Root",
    SEARCH_RULES = "Search Rules",
    CREATE_CHANGE_ORDER_REQUISITION_BASED_ON_BELOW_SELECTED_BASE_REQUISITION="Create change order requisition based on below selected base requisition",
    COPY_HEADER_TEXT_FROM_PACKAGE="Copy header text from Package"
  
  }

  export enum CommonKeys {
    SEARCH_RESULT = "search_result",
    PATH = "path",
    FILTER = "Filter",
    MANUAL_INPUT = "Manual Input",
    CODE = "Code",
    ADDRESS_INDEX = "address_index",
    VALUE = "Value",
    SELECTION = "Selection",
    BUTTON_TAG = "button",
    LOGIN_VIEW = "loginView",
    MENU_MAIN = "menu main",
    RADIO = "radio",
    BUTTON_HANDLE = "Button",
    GRID = "grid",
    LIST = "list",
    LIST_EXACT = "listexact",
    GRID_1 = "grid1",
    SPAN = "span",
    WIZARD = "wizard",
    CHECKED = "Checked",
    CHECK = "check",
    UNCHECK = "uncheck",
    SUBMITTED = "Submitted",
    APPROVED = "Approved",
    PROCESSED = "Processed",
    PART_DELIVERED= "Part Delivered",
    AVAILABLE = "Available",
    DELIVERED = "Delivered",
    DATE_RECEIVED = "Date Received",
    FI_BILLED = "FI Billed",
    ACCEPTION = "Acception",
    PUBLISHED = "Published",
    IN_PROGRESS = "In-Progress",
    STANDARD = "standard",
    MATERIAL = "Material",
    MATERIAL_AND_COST_CODE = "Material & Cost Code",
    QUICKSTART = "quickstart",
    RADIO_INDEX = "Radio Index",
    CHECKBOX = "Checkbox",
    DEFAULT = "Default",
    IN_MINUS_PROGRESS = "In-Progress",
    FILTER_SMALL = "filter",
    INDEX = "Index",
    ROOT = "Root",
    POSITION = "Position",
    CONTRACTED = "Contracted",
    A = "a",
    LABEL = "label",
    DIV = "div",
    LI="li",
    CLASS = "class",
    NEW_CONFIG_NAME = "New Config Name",
    TOTAL = "Total",
    NO_FILTER="noFilter",
    CURRENT_SMALL="current",
    INCREMENTED_SMALL="incremented",
    BASE_COST_TOTAL="Base Cost Total",
    VALIDATION_WIZARD= "Validation Wizard",
    ROUNDING="Rounding",
    WITHOUT_ROUNDING="WithoutRounding",
    QUANTITY="QUANTITY",
    FINAL_PRICE="FINAL_PRICE",
    UNIT_RATE="UNIT_RATE",
    FINAL_PRICE_IN='FINAL_PRICE_IN',
    BOTH="Both",
    EDIT="edit",
    SCHEDULES="Schedules",
    FROM_STRUCTURE="From Structure",
    PAYMENT_TERM="Payment Terms",
    CONTROLLING_UNITS="Controlling Units",
    CONTROLLING_UNIT="Controlling Unit",
    TO_STRUCTURE="To Structure",
    RECORDED = "Recorded",
    TO_STRUCTURE_AQ="ToStructure AQ",
    BIDIRECTIONAL_WQ_AQ="Bidirectional WQ AQ",
    IS_DUE="Is Due",
    PROJECT_COST_GROUP="Project Cost Group",
    CREATE="create",
    ENTERPRISE_COST_GROUP="Enterprise Cost Group",
    LOCATION="Location",
    NO_RELATION="No relation",
    BOQS="BoQs",
    ACTIVE="Active",
    SELECT_RADIO_BUTTON="selectRadioButton",
    SCHEDULING="Scheduling",
    NOT_VISIBLE="notVisible",
    NOT_VISIBLE_COLUMN="notVisibleColumn",
    INPUT_SHOULD_NOT_EXIST="inputShouldNotExist",
    IN_ARBEIT="In Arbeit",
    PROJECT_ESTIMATE="Project Estimate",
    ALLOWANCE="Allowance",
    ESTIMATE_ALLOWANCE="Estimate Allowance",
    ESTIMATE_ALLOWANCE_TYPE="Est. Allowance Assignment Type",
    CO2_PROJECT_TOTAL="co2projecttotal",
    CO2_SOURCE_TOTAL="co2sourcetotal",
    CO2_TOTAL_VARIANCE="co2totalvariance",
    ESTIMATE_COST_CODE="Estimate Cost Code",
    INFORMATION="Information",
    ASSEMBLIES="Assemblies",
    INCREMENTED="incremented",
    CURRENT="current",
    SHOULD_NOT_EXIST="shouldNotExist",
    SHOULD_EXIST="shouldExist",
    VISIBLE="Visible",
    NOT_SPACE_VISIBLE="not visible",
    VISIBLE_SMALL="visible",
    COST_CODE_TYPE="Cost Code Type",
    ASSEMBLY_TYPE="Assembly Type",
    EST_ASSEMBLY_TYPE="Est. Assembly Type",
    CREW_ASSEMBLY="Crew Assembly",
    STANDARD_ASSEMBLY="Standard Assembly",
    PROGRESS_INVOICE="Progress Invoice",
    BPA_BILLED="BPA Billed",
    MODAL_FOOTER="modal-footer",
    USER="user",
    USER_DEFINED_COST_COLUMNS="User Defined Cost Columns",
	  LAYOUT_6="layout6",
    WIC_ITEM_REF_NO="WICItemRefNo",
    STATUS_BAR="statusbar",
    VALID = "Valid",
    SELECT_MAINTENANCE="Select Maintenances",
    HOOK="Hook",
    SALES_WIP_AND_BILL='Sales / WIP&Bill',
    CHANGE_ORDER="Change Order",
    PROJECT_BOQ="Project BoQ",
    LAYOUT_19="layout19",
    TARGET="Target",
    ONE_BID_FOR_ALL_CHANGES="One bid for all changes",
    SEPARATE_BID_FOR_EACH_CHANGE="Separate bid for each change",
    PLANNED="Planned",
    STARTED="Started",
    FINISHED="Finished",
    CHANGE_BID="Change Bid",
    IDENTIFIED="Identified",
    DESIGN_CHANGE="Design Change",
    CHANGE_REQUEST="Change Request",
    CHANGE_CONTRACT="Change Contract",
    POSTED="Posted",
    FINAL_INVOICE="Final Invoice",
    GENEHMIGTER_NETTOBETRAG="Genehmigter Nettobetrag",
    LAYOUT_21="layout21",
    BILLED="Billed",
    FROM_PESS="From PES",
    COLLAPSE="Collapse",
    INVOICES="Invoices",
    NETTO="Netto",
    STANDARD_SINGEL="Standard Singel",
    CREATE_ONE_INVOICE_PER_PES="Create one invoice per PES",
    AMOUNT="Amount",
    FROM_CONTRACT_ITEMS="From Contract Items",
    FROM_OTHER="From Other",
    REJECTIONS="Rejections",
    FROM_BILLING_SCHEMA="From Billing Schema",
    BALANCE="Balance",
    CLERK="Clerk",
    RECHNUNGSKORREKTUR="Rechnungskorrektur",
    HISTORY = "History",
    NEW = "New",
    BOQ="BoQ",
    WIC_BOQ="WIC BoQ",
    LAYOUT_2="layout2",
    USER_FREQUENCE="User Frequence",
    WIP="WIP",
    OFFER_ISSUED="Offer issued",
    FREIG_LEISTUNG_STAND="Freig. Leistungsstand",
    SERVICE_PERSONNEL="Service Personnel",
    FIND_BIDDER="Find Bidder",
    PACKAGE_STATUS="Package Status",
    PROGRESS="Progress",
    WIP1="WIP1",
    MATERIAL_CATALOG_AND_GROUP="Material Catalog & Group",
    LEVEL_2="Level 2",
    LEVEL_1="Level 1",
    PRICE_COMPARISON_1="Price Comparison(1)",
    MATERIAL_CATALOG_TYPE="Material Catalog Type",
    INTERNET_CATALOG="internet catalog",
    NEUTRAL_MATERIAL="Neutral Material",
    MATERIAL_TYPE="Material Type",
    STOCK_MANAGED_MATERIAL="Stock Managed Material",
    MASTER_DATA="Masterdata",
    CATALOG_DOES_NOT_EXISTS="catalogdoesnotexists",
    CATALOG_EXISTS="catalogexists",
    DROP_DOWN="dropdown",
    SEARCH_TERM="searchterm",
    ATTRIBUTE="attribute",
    ICON="icon",
    MIN_QUANTITY="minQuantity",
    MATERIAL_TYPE_SMALL="materialType",
    SORTING_LOW_TO_HIGH="sortingLowToHigh",
    SORTING_HIGH_TO_LOW="sortingHighToLow",
    LIST_PRICE="listPrice",
    CART_RECORD="cartRecord",
    ALTERNATIVE="alternative",
    DETAILS_CO2_ATTRIBUTE_PRICE_LIST="detailsCO2AttributePriceList",
    PERCENT="Percent",
    PROJECT_MANAGER="Project Manager",
    CERTIFICATE_TYPE="Certificate Type",
    CIS_CERTIFICATE_EN="CIS Certificate (en)",
    PLACE_ORDER_SUCCESSFULLY="Place Order Successfully",
    DISABLED="disabled",
    ENABLED="enabled",
    SERVICE="Service",
    PACKAGE="Package",
    CONSTRUCTION="Construction",
    INFO_TEXT="Info Text",
    INVOICE_FOOTER="Invoice Footer",
    INTERNAL_FOOTER="Internal Footer",
    QUANTITY_SMALL="Quantity",
    ORDERED="Ordered",
    SELECTED_ITEMS="Selected item(s)",
    BASE_PRICE="Base Price",
    ALTERNATIVE_CAPS="Alternative",
    BASE_POSTPONED="Base postponed",
    ALTERNATIVE_AWARDED="Alternative awarded",
    DISABLE_TARGET_ITEM_AFTER_REPLACEMENT="Disable Target Item After Replacement",
    PACKAGE_1="Package(1)",
    BLOCKED="Blocked",
    MATERIAL_REQ="Material Req",
    GENERAL="General",
    CONVERSION="Conversion",
    UNIT="Unit",
    GRAM="Gram",
    KILOGRAM="Kilogram",
    ALL_QUOTE_FROM_CURRENT_PROJECT="All Quotes from Current Project",
    SPECIFIC_CATALOG="Specific catalog",
    MATERIAL_PO="Material PO",
    CONTRACT="Contract",
    SUPPLIER_TEXT="Supplier Text",
    CONTRACT_SALUTATION="Contract Salutation",
    PROCURMENT_EVENT_TYPES="Procurement Event Types",
    DESIGN_READY="Design Ready",
    SYSYTEM_OPTION="System Option",
    AUTO_UPDATE_CHAINED_EVENTS="Auto Update Chained Events",
    BEFORE_EVENT_END= "Before Event End",
    AFTER_EVENT_START= "After Event Start",
    AFTER_CUSTOM_EVENT_START= "After Custom Event Start",
    AFTER_CUSTOM_EVENT_END= "After Custom Event End",
    BEFORE_CUSTOM_EVENT_START= "Before Custom Event Start",
    BEFORE_CUSTOM_EVENT_END= "Before Custom Event End",
    BEFORE_SYSTEM_EVENT= "Before System Event",
    PLANNED_END_PACKAGE= "Planned End (Package)",
    AFTER_SYSTEM_EVENT= "After System Event",
    ACTUAL_START_PACKAGE= "Actual Start (Package)",
    ACTUAL_END_PACKAGE= "Actual End (Package)",
    SAFETY_LEAD_TIME= "Safety Lead Time",
    PLANNED_START_PACKAGE= "Planned Start (Package)",
    NO_START_DATE="No Start Date",
    NO_END_DATE="No End Date",
    FETCHED_DATE_INCREMENT="fetchedDateIncrement",
    FETCHED_DATE_DECREMENT="fetchedDateDecrement",
    BYPASS_EVALUATED_ITEM="Bypass evaluated item",
    INCLUDE_NON_CONTRACTED_ITEM_IN_PREVIOUS_PES="Include non contracted item in previous PES",
    REQUISITION_STATUS="Requisition Status",
    NSTB="NSTB",
    DOWNWARDS="Downwards",
    LAYOUT_1="layout1",
    PROCUREMENT_BUDJET = "Procurement Budget",
    NET_TOTAL="Net Total",
    SERVICE_PA="Service PA",
    ALLOCATION='Allocation',
    RECONCILIATION="Reconciliation",
    DISCOUNT_AMOUNT="Discount Amount",
    DISCOUNT_BASIS="Discount Basis",
    DISCOUNT_DATE="Discount Date",
    NET_PAYABLE="Net Paybel",
    INVOICE_TYPE="Invoice Type",
    INVOICE='Invoice',
    PROCUREMENT_BUDGET = "Procurement Budget",
    FRAMEWORK_AGREEMENTS="framework agreements",
    CHANGE_STRUCTURE="Change Structure",
    NEW_REQUISITION="New Requisition",
    HEADER="HEADER",
    TODAY="Today",
    DATE_REQUESTED="Date Requested",
    PURCHASE_ORDER="Purchase Order",
    RFQ_CREATED="RfQ Created",
    CRITERIA_LABEL="Criteria Label",
    CRITERIA="Criteria",
    CRITERIA_1="Criteria 1",
    CRITERIA_2="Criteria 2",
    RIB_DEMO_STAMM="RIB_DEMO_Stamm",
    HIGHLIGHTED_MATERIAL="Highlighted Material",
    CURRENT_CONTRACT="Current Contract",
    ALL_CONTRACTS_FROM_CURRENT_PROJECT="All Contracts from Current Project",
    ALL_CATALOGS="All catalogs",
    BY_IDENTICAL_MATERIAL_CODE="By identical material code",
    BY_PROCUREMENT_STRUCTURE="By procurement structure",
    SELECTED_LINE_ITEM="Selected Line Item",
    CRITERIA_SELECTION="Criteria Selection",
    CURRENT_RESULT_SET="Current Result Set",
    PERFECTLY_MATCHED="Perfectly Matched",
    PES_STATUS="PES Status",
    ONE_TRANSACTION_PER_PES_ITEM="One Transaction per PES Item",
    TRANSCATION_MODE="Transaction Mode",
    COMPANY_YEAR="Company Year",
    REPORTING_PERIOD="Reporting Period",
    YEAR="year",
    CREATE_TRANSACTION="Create Transaction",
    LINE_ITEMS="Line Items",
    FIXED_TIME="Fixed Time",
    DAY="Day",
    FIXED_UNITS="Fixed Units",
    NACHUNTERNEHMER="Nachunternehmer",
    FIXED_WORK="Fixed Work",
    FINLAND="Finland",
    LAYOUT_0="layout0",
    PRICE="Price",
    MODIFICATION ="modification",
    AS_SOON_AS_POSSIBLE="As Soon As Possible",
    M="M",
    DE="DE",
    MANUAL="manual",
    TENDERING="Tendering",
    SIDE_ORDER= "Side Contract",
    CONSECUTIVE_BILL_NO="Consecutive Bill No.",
    CUSTOMER="Customer",
    BILL_NO="Bill No.",
    TRANSPORT_PLANNING="Transport Planning",
    PICKING="Picking",
    LOADED="Loaded",
    SERVICE_REQ = "Service REQ",
    ACTIVITY="Activity",
    BOQ_ITEM_REF_NO="BoQ Item Ref. No.",
    LIMITS="Limits",
    WEEKLY_LIMIT="Weekly Limit",
    MONTHLY_LIMIT="Monthly Limit",
    TIME_SYMBOL_LIMITS="Time Symbol Limits",
    TIME_SYMBOL_BEFORE_DAILY_LIMIT="Time Symbol before daily limit",
    TIME_SYMBOL_SAVING_LIMITS="Time Symbol Saving Limits",
    TIME_SYMBOL_FOR_HRS_OVER_SAVING_LIMIT="Time symbol for hrs over saving limit",
    GA ="G&A",
    RP="R&P",
    AM= "AM",
    ACCOUNTING="Accounting",
    ORDER_TEXT="Order Text",
    BOQ_CATALOG_ASSIGN_DETAILS="BoQ Catalog Assign Details"
    
  }

  export enum  CommonGridLayout{
    AllColumnsToLeft=`.middle-container .ico-ar1-left2`,
    ColumnToRight=`.middle-container .ico-ar1-right1`,
    AllColumnToRight=`.middle-container .ico-ar1-right2`
  }

  export enum CommonElements {
    // This enum includes inputs,classes,button,id
    POPUP_FOOTER = "[class*='popup-footer']",
    CARET_MODAL = "[class*='btn btn-default dropdown-toggle']",
    ICO_DISCARD = ".ico-discard",
    ACTIVE = "[class*='active']",
    BOQ_FOLDER_ICON = "[class*='ico-folder-doc']",
    BOQ_ITEM_ICON = "[class*='ico-boq-item']",
    SUBCONTAINER_INMODEL = "[ng-controller='boqMainStructureDetailsController'] [class*='subview-container']",
    MENUMAIN = "menu main",
    MENU="menu",
    LOGINVIEW = "loginView",
    CARET = "[class*='caret']",
    ICON_TICK = "[class*='ico-tick']",
    NO_TICK = "[class*='control-icons ']",
    SUBVIEW = "[class*='subview-content']",
    SEARCH_ICON = "[class*='ico-indicator-search']",
    SEARCH = "[class*='ico-sdb-search2']",
    SEARCH_FORM = "[class*='ico-sdb-search3']",
    ICO_MENU = "[class*='ico-menu']",
    SEARCH_BUTTON = "[class*='search-button']",
    SEARCH1 = "[class*='ico-sdb-search1']",
    ICO_TREE_COLLAPSE = "[class*='ico-tree-collapse']",
    INPUT_TEXT = "input[type=text]",
    CHECK_TICK = "[class='fa fa-check']",
    CHECKBOX_INPUT = "[type='checkbox']",
    SPECIFIC_CATALOG_INPUT = '[class*="input-group-content"]',
    CHECKBOX_TYPE = "[type='checkbox']",
    CHARACTERISTIC_LABEL = "[class*='tree-label']",
    MODAL_FLEX_ELEMENT = "[class*='flex-element']",
    RADIO_INPUT = "[type='radio']",
    GROUP_BTN = "[class*='input-group-btn']",
    RADIO_CLASS = "[class*='radio']",
    SEARCH_TERM_INPUT = "input[placeholder='Search Term']",
    GRID_CONFIGURATOR_ID = "[id='gridConfigurator']",
    COLUMN_ID = "column-id_",
    GRID_LAYOUT = "[class*='popup-menu'] button[title='Grid Layout']",
    ICON_SETTING = "button[class$='ico-settings']",
    WIZARD_POPUP_MESSAGE = "[class='message ng-binding']",
    CODE_MIRROR = "[class*=' CodeMirror-line ']",
    CONTRACT_POPUP_MESSAGE = "[class='message selectable ng-binding']",
    CHANGE_STATUS_VALUES = "[class*='change-status-detail-item ng-scope']",
    POP_UP_MODAL = "div.message",
    BRANCH_CONTAINER = "branch-container",
    CONTACT_CONTAINER = "contact-container",
    INVALID_CELL = "invalid-cell",
    REQUIRED_CELL = "required-cell",
    CELL_READONLY = "cell-readonly",
    FULL_WIDTH = " .fullwidth",
    COST = "[title='Cost']",
    DESC = ".column-id_desc",
    STYLE_RED = "color:red;",
    STYLE_GREEN = "color:green;",
    BOQ_OUT_SPEC = "[class*=`briefinfo`]",
    MARKER = "marker",
    IS_MARKED = "IsMarked",
    REVERT_BUTTON = "div[class*=ms-sv-revert-button]",
    LOOKUP_DROPDOWN = "[class*='button bg-color-bar1 control-icons ico-down']",
    SEARCH_RESULT_COLUMN = "[class*='col-md-9 ms-sv-result-panel-right']",
    SEARCH_RESULT_ROW = "[class*='row ms-sv-commodity-result-pane']",
    MASTER_ITEM = "[class='master-item']",
    HEADER_TEXT_CONTAINER = "[class*='ql-container']",
    HEADER_TEXT_DESCRIPTION = "[class*='ql-editor ql-blank']",
    PANEL_GROUP = "[class*='panel-group']",
    PLATFORM_FORM_GROUP_HEADER_TEXT = "[class*='platform-form-group-header-text']",
    ROW = "[class*='platform-form-row']",
    ROW_READONLY = "row-readonly",
    PLATFORM_FORM_LABEL = "[class*='platform-form-label']",
    TITLE = "[class*='item-title']",
    MATERIAL_ROW = "div.flex-box div.ms-commodity-row",
    MATERIAL_TITLE = "span.ms-commodity-row-item-title",
    LINE_TYPE = "[class*='column-id_lineTyp']",
    START_VALUE = "[class*='column-id_val selected']",
    STEP_INC = "[class*='column-id_stepInc selected']",
    PLS_IN_TEXT_AREA = "[class*='k-content-frame']",
    FLEX_BOX = "[class*='flex-box']",
    CART_VIEW_MATERIALS_HEADER = "[id='cart-view-materials-header']",
    PROC_STRUCTURE = "Proc.Structure",
    SIDEBAR = "[class='sidebar ng-scope expanded']",
    RULE = "[class*='rule']",
    TABLE_SELECTION = "[class*='fullheight k-pane k-scrollable']",
    SUB_VIEW = "[class*='subview-content']",
    RIGHT_COLUMN = "[class*='slick-headerrow-columns-right']",
    NAME = "[class*='item-field_name']",
    LEFT_COLUMN = "[class*='slick-headerrow-columns-left']",
    RULE_OPERAND = "[class*='rule-editor-operand-element']",
    RULE_DESCRIPTION = "[class*='domain-type-description']",
    DROPDOWN_MENU = "[class*='dropdown-menu']",
    CARET_SELECTION = "[class*='domain-type-select']",
    PLATFORM_GROUP = "[class*='platform-form-group']",
    TICKET_SYSTEM_ORDER_LIST = "div.ticket-system-order-list-cell",
    TICKET_SYSTEM_ORDER_LIST_HEADER = "div.ticket-system-order-list-header",
    TICKET_SYSTEM_ORDER_ATTRIBUTE_STATUS = "div.ticket-system-order-list-attribute-status",
    TICKET_SYSTEM_ORDER_LIST_BUTTON = "div.ticket-system-order-list-showbtn",
    TICKET_TOTAL = `[class*="ts-cart-item-total-panel"]`,
    TRANSACTION_INPUT_ROW = "[class='row pes-row']",
    PLATFORM_FORM_COL = "[class*='platform-form-col']",
    BUTTON = "[type='button']",
    SELECT_CHECKBOX = "checkbox-radio-box",
    PLATFORM_COL = "platform-form-col",
    VISIBLE = "[class*='visible']",
    VISIBLE_CHECKBOX = "[class*='column-id_Visible selected']",
    GRID_CONTAINER = "[class*='grid-container']",
    BID_BOQ_TAB = "[class='nav nav-tabs'] [heading='BoQ']",
    BID_BASIC_TAB = "[class='nav nav-tabs'] [heading='Basics']",
    POPUP_CONTAINER = ".popup-container",
    ICON = "[class*='block-image']",
    SUB_VIEW_CONTAINER = "[class*='subview-container']",
    RADIO1 = "platform-form-row form-group",
    COLUMN_READONLY = "column-readonly",
    CLASS_SELECTED = "[class*='selected']",
    BODY = "body",
    VIEW_DESCRIPTION = "div.popup-content ul>li>button[data-ng-bind='view.Description']",
    GRID_CANVAS_RIGHT = "[class*='grid-canvas grid-canvas-top grid-canvas-right']",
    UI_WIDGET_CONTENT = "[class*='ui-widget-content']",
    LOOKUP_ITEM = "[class*='lookup-item']",
    ACTIVE_CHECKBOX = ".active [class*='column-id_selected']",
    ACCORDION_ROOT = "[class*='ico-accordion-root']",
    RADIO_SPACE_TO_UP = "radio spaceToUp",
    LABEL = "label",
    LABEL_FOR_INCLUDE_NON_ACTIVE_ITEMS_ID = "label[for='includeNonActiveItemsId']",
    PLATFORM_FORM_ROW="platform-form-row",
    ESTIMATE_SELECT_CRITERIA_PLATFORM_FORM_ROW="estimate-select-criteria platform-form-row",
    DOMAIN_TYPE_CODE="[class*='domain-type-code']",
    DOMAIN_TYPE_TRANSLATION="[class*='domain-type-translation']",
    USE_IN_SPLIT="[class*=`selected item-field_Delete column-id_useinsplit]",
    NAV_TABS="[class*='nav-tabs']",
    DOMAIN_TYPE_RADIO="[class*=`domain-type-radio`]",
    MATERIALCATALOG_BUTTON="[data-options='materialOptionList']",
    TD_HEADER_STYLE= 'tdHeaderStyle',
    GRID_Layout_LEFT_ID="[id='fffffe94db154e72bed8fb879b08ffff']"

    
  }

}
export default CommonLocators;
